server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: foo
    password: 123456
    #url中database为对应的数据库名称
    url: jdbc:mysql://117.50.182.208:3306/ordering_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/static/
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
      connect-timeout: 30000ms

mybatis:
  type-aliases-package: com.cook.baolema.pojo

alipay:
  appId: 2021000122627772
  appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCRT9d2tu9OyZgVrNt9yRCELRUUFLHY+r3CbIDGuDMtBBUWQno3ugWMEH9INzIymnSTUu1GgkaCfkoHB1FBIZjyLwOt7o9P35TXQOM93jLeVt/KihVnWdGNOajKkbLAC9uDTW3A4IvsIctIoPWf8e4FbtBkqXE5xwql4LlRUKRJoMjLFn67PMrBQzUMJiYaEPi0/sgkKyLbB/NWg9D4IMszSVxiOGPL7KvLBaHFBZEGPGWgCqSVASoVhMxEOMeSLlO6XCJOeOsLcBwPoz0914/4bXDBPS5BjVQW0wkje4e4H0SSMSeAWqpdFeZbveUR5K43AReHbKi22wvfLdhckMyjAgMBAAECggEBAIfWa0S+nda4/ULF5Ckh3B6zRhEPh3Gec+VcKMWbS7u5JT05x6Zwbt8QTOvlLTfAy1ktHEHdZqx2Ah2v6XVJQwCikn31lGLGTw0py0P6gvL1ox5jFr8WZ53tWKyEpuSAMSP9LawwPJzwumeakAKE1kyd2pE/FGk+d+W4vYQWLn3kNfAJ9zErd9MMLVGcCC3g9+5E94wJdiBpwFQTYHepuz83bY11fIk47Z6xtjKCJDpa/0k/wIlrzOkiw45YlgXUIdypz2dovfFVYWgaz4XGB9vfKYkED3yj52TFxm7JsxJB/yO3F+wbqUKRKwWz82Y4sJNsGSu5mbR4MFLlvD3J0IECgYEA0coTSBIOa8kbFj3fJebGwhIv5Dkry23pu3wdxynE/BeTIA9oRcdYSLHVDBmGxFiFrLjhnPVdN+f1dQ9ccyPe2X6JSZWa7gMRVKr3+5ejRcQp92x+NKzMZtxgjiqoLr1Q2lVAcSVMnmwtldiFaalnoZ6vFfwfbI7SVIeoCMc+me0CgYEAsVHpTya6zWzf2FizmrwtX45t6+/Ol8T4X5NyUjv2o/KEGwH3/WWATRH4zfJlofiIA9VQKvQH317E101YzS70DNmxom2eHdFmHzBEmOWQB3jDjTh5m4I4QG41Dsa/jL6t+6F4DTDrUycE335YIoLY0SygLW/x82w4s0i4wqo47s8CgYAV3DWoI+GGz7zX03imLWb2oAiHgoGSwBBD7gn4T9zr29UD2TcnVj9Xy9gEW8CUQxkix10TCuo8whnsqb4bbVhyV2Ic3c74EC/FH8+ZUtK7mVY6Jv77pCnkagBRsBY4UJfVOF7vq1BRjbouTBKS0QkwaSWbZ9sqZ7N5BW24BHL8fQKBgQCEylnVe6STKICt7Sd7roawM+KfuPPW9pwmPy5y5RL8jiZeb2f+7N9bWCUiXe+8j3mUnU+vCxdGMRtqPTNOXWZIpVKA2GR74g//NU95zRjCb67KeEuhqLBll+LGERLr3PRAKBjWkBb7K5JbqKtqFOE4LJo7zMS9zgLcSI6MwZtnQwKBgQCyMInq97H5bDC3IYOdjkLSlKj2Qkaz4ZK7JL1gFpdl53/YrYcamq54AYIIIURkJZtNM58FhLsnSwWebpE8hZP9QpuPRR5Y7JD78AjvKZRVKxoZo+oLoAeh/5PDe3S/KB4sBgNX+z96Wy/xErezmvIofuOvA2VQdV5k8o5/RaZ9zA==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkU/XdrbvTsmYFazbfckQhC0VFBSx2Pq9wmyAxrgzLQQVFkJ6N7oFjBB/SDcyMpp0k1LtRoJGgn5KBwdRQSGY8i8Dre6PT9+U10DjPd4y3lbfyooVZ1nRjTmoypGywAvbg01twOCL7CHLSKD1n/HuBW7QZKlxOccKpeC5UVCkSaDIyxZ+uzzKwUM1DCYmGhD4tP7IJCsi2wfzVoPQ+CDLM0lcYjhjy+yrywWhxQWRBjxloAqklQEqFYTMRDjHki5TulwiTnjrC3AcD6M9PdeP+G1wwT0uQY1UFtMJI3uHuB9EkjEngFqqXRXmW73lEeSuNwEXh2yottsL3y3YXJDMowIDAQAB
  notifyUrl:


