server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: foo
    password: 123456
    #url中database为对应的数据库名称
    url: jdbc:mysql://117.50.182.208:3306/ordering_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/static/

mybatis:
  type-aliases-package: com.cook.baolema.pojo


